CREATE TABLE user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  active TINYINT(1) DEFAULT 1 NOT NULL
);