CREATE TABLE product (
  uuid VARCHAR(36) NOT NULL PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE,
  price DOUBLE NOT NULL,
  stock BIGINT NOT NULL,
  active TINYINT(1) DEFAULT 1 NOT NULL
);