CREATE TABLE product (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE,
  price DECIMAL NOT NULL,
  stock BIGINT NOT NULL,
  active TINYINT(1) DEFAULT 1 NOT NULL
);