CREATE TABLE purchase (
  uuid VARCHAR(36) NOT NULL PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  total DOUBLE NOT NULL,
  situation ENUM('CONFIRMED', 'CANCELED', 'INSUFFICIENT_STOCK') NOT NULL,
  createAt DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (uuid)
);